
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('students').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('students').insert({ id: 1, name: 'Salazar' }),
        knex('students').insert({ id: 2, name: 'Martin S.' }),
        knex('students').insert({ id: 3, name: 'Frampton' }),
        knex('students').insert({ id: 4, name: 'Yost' }),
        knex('students').insert({ id: 5, name: 'Prokhnitski' }),
        knex('students').insert({ id: 6, name: 'Ju' }),
        knex('students').insert({ id: 7, name: 'Reyes' }),
        knex('students').insert({ id: 8, name: 'Riegler' }),
        knex('students').insert({ id: 9, name: 'Kirshling' }),
        knex('students').insert({ id: 10, name: 'Herbert' }),
        knex('students').insert({ id: 11, name: 'Munoz' }),
        knex('students').insert({ id: 12, name: 'Smith B.' }),
        knex('students').insert({ id: 13, name: 'Smith A.' }),
        knex('students').insert({ id: 14, name: 'Sipe' }),
        knex('students').insert({ id: 15, name: 'Anderson' }),
        knex('students').insert({ id: 16, name: 'Broderick' }),
        knex('students').insert({ id: 17, name: 'Crase' }),
        knex('students').insert({ id: 18, name: 'Lark' }),
        knex('students').insert({ id: 19, name: 'Kizhnerman' }),
        knex('students').insert({ id: 20, name: 'Wolf' }),
        knex('students').insert({ id: 21, name: 'Mendelsberg' }),
        knex('students').insert({ id: 22, name: 'Travaglia' }),
        knex('students').insert({ id: 23, name: 'Jacobson A.' }),
        knex('students').insert({ id: 24, name: 'Jacobson I.' }),
        knex('students').insert({ id: 25, name: 'Shurley' }),
        knex('students').insert({ id: 28, name: 'Engelhardt' }),
        knex('students').insert({ id: 29, name: 'Fierro' }),
        knex('students').insert({ id: 30, name: 'Bowen' }),
        knex('students').insert({ id: 31, name: 'Martin M.' }),
        knex('students').insert({ id: 32, name: 'Smith So.' }),
        knex('students').insert({ id: 33, name: 'Evans' }),
        knex('students').insert({ id: 34, name: 'Larchick' }),
        knex('students').insert({ id: 35, name: 'Vassine' }),
        knex('students').insert({ id: 36, name: 'Heilmann' }),
        knex('students').insert({ id: 37, name: 'White' }),
        knex('students').insert({ id: 38, name: 'Saavedra' }),
        knex('students').insert({ id: 39, name: 'Rosenwinkel' }),
        knex('students').insert({ id: 40, name: 'Pozzi' }),
        knex('students').insert({ id: 41, name: 'Beckwith' }),
        knex('students').insert({ id: 42, name: 'Terrazas' }),
        knex('students').insert({ id: 43, name: 'Strother' }),
        knex('students').insert({ id: 44, name: 'Leisegang' }),
        knex('students').insert({ id: 46, name: 'Evanson' }),
        knex('students').insert({ id: 47, name: 'Hardin' }),
        knex('students').insert({ id: 48, name: 'Harrison St.' }),
        knex('students').insert({ id: 49, name: 'Schnurrenberger' }),
        knex('students').insert({ id: 50, name: 'Liebgott' }),
        knex('students').insert({ id: 51, name: 'Montoya' }),
        knex('students').insert({ id: 52, name: 'Donahue' }),
        knex('students').insert({ id: 53, name: 'Kust' }),
        knex('students').insert({ id: 54, name: 'Moskovich' }),
        knex('students').insert({ id: 55, name: 'Whitney' }),
        knex('students').insert({ id: 56, name: 'Smith T.' }),
        knex('students').insert({ id: 57, name: 'Harrison Sc.' }),
        knex('students').insert({ id: 58, name: 'Marquez' }),
        knex('students').insert({ id: 59, name: 'Schmid' }),
        knex('students').insert({ id: 60, name: 'Romero' }),
        knex('students').insert({ id: 61, name: 'Noyes' }),
        knex('students').insert({ id: 62, name: 'Waryn' }),
        knex('students').insert({ id: 63, name: 'May' }),
        knex('students').insert({ id: 64, name: 'Treitz' }),
        knex('students').insert({ id: 65, name: 'Nagy' }),
        knex('students').insert({ id: 66, name: 'Jacques' }),
        knex('students').insert({ id: 67, name: 'Letendre' }),
        knex('students').insert({ id: 68, name: 'Smith Se.' }),
        knex('students').insert({ id: 69, name: 'Shearer' }),
        knex('students').insert({ id: 70, name: 'Miripol' }),
        knex('students').insert({ id: 71, name: 'Strout' }),
        knex('students').insert({ id: 72, name: 'Ridgway' }),
        knex('students').insert({ id: 73, name: 'Ruff' }),
        knex('students').insert({ id: 74, name: 'Milshtein' }),
        knex('students').insert({ id: 75, name: 'Brower' }),
        knex('students').insert({ id: 76, name: 'Savavi D.' }),
        knex('students').insert({ id: 77, name: 'Savavi A.' }),
        knex('students').insert({ id: 78, name: 'Lashnits' })
      ]);
    });
};
